### ISSUE TITLE
Docs: 404 page not found for the tutorial

### ISSUE THREAD

**Issue by mkubdev** [carbon-design-system/carbon-tutorial-nextjs#33]
## Detailed description

The Get started link in the repo's readme, pointing to the [tutorial instructions](https://carbondesignsystem.com/developing/next-tutorial/overview/) (from #24 addition), is leading to a 404 error. It seems that the page at https://carbondesignsystem.com/developing/next-tutorial/overview doesn't exist (yet?) on the main website.

## Steps to reproduce the issue

1. Navigate to https://github.com/carbon-design-system/carbon-tutorial-nextjs.
2. Click on the tutorial instructions link in the readme.

## Additional information

![image](https://github.com/carbon-design-system/carbon-tutorial-nextjs/assets/50140834/891e144c-4f62-4ca0-a1a0-276aaa788e72)

**Comment by tay1orjones** [comment]
@mkubdev Yes we haven't fully published this updated tutorial yet. Keep an eye out though, it'll be live on the site soon https://github.com/carbon-design-system/carbon-website/pull/3710 with an accompanying Medium article on [our publication](https://medium.com/carbondesign).

**Comment by mkubdev** [comment]
@tay1orjones Oh ok! Sure, very nice design system 🙏 I'm closing.
